// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public interface BallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protobuf.Ball)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double x = 1;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 2;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double z = 3;</code>
   * @return The z.
   */
  double getZ();

  /**
   * <code>double vx = 4;</code>
   * @return The vx.
   */
  double getVx();

  /**
   * <code>double vy = 5;</code>
   * @return The vy.
   */
  double getVy();

  /**
   * <code>double vz = 6;</code>
   * @return The vz.
   */
  double getVz();
}
