// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public interface EnvironmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protobuf.Environment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 step = 1;</code>
   * @return The step.
   */
  int getStep();

  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   * @return Whether the frame field is set.
   */
  boolean hasFrame();
  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   * @return The frame.
   */
  Protobuf.Frame getFrame();
  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   */
  Protobuf.FrameOrBuilder getFrameOrBuilder();

  /**
   * <code>.Protobuf.Field field = 3;</code>
   * @return Whether the field field is set.
   */
  boolean hasField();
  /**
   * <code>.Protobuf.Field field = 3;</code>
   * @return The field.
   */
  Protobuf.Field getField();
  /**
   * <code>.Protobuf.Field field = 3;</code>
   */
  Protobuf.FieldOrBuilder getFieldOrBuilder();

  /**
   * <code>uint32 goals_blue = 4;</code>
   * @return The goalsBlue.
   */
  int getGoalsBlue();

  /**
   * <code>uint32 goals_yellow = 5;</code>
   * @return The goalsYellow.
   */
  int getGoalsYellow();
}
