// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

/**
 * Protobuf type {@code Protobuf.Environment}
 */
public final class Environment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protobuf.Environment)
    EnvironmentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Environment.newBuilder() to construct.
  private Environment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Environment() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Environment();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Environment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Environment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Protobuf.Environment.class, Protobuf.Environment.Builder.class);
  }

  private int bitField0_;
  public static final int STEP_FIELD_NUMBER = 1;
  private int step_ = 0;
  /**
   * <code>uint32 step = 1;</code>
   * @return The step.
   */
  @java.lang.Override
  public int getStep() {
    return step_;
  }

  public static final int FRAME_FIELD_NUMBER = 2;
  private Protobuf.Frame frame_;
  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   * @return Whether the frame field is set.
   */
  @java.lang.Override
  public boolean hasFrame() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   * @return The frame.
   */
  @java.lang.Override
  public Protobuf.Frame getFrame() {
    return frame_ == null ? Protobuf.Frame.getDefaultInstance() : frame_;
  }
  /**
   * <code>.Protobuf.Frame frame = 2;</code>
   */
  @java.lang.Override
  public Protobuf.FrameOrBuilder getFrameOrBuilder() {
    return frame_ == null ? Protobuf.Frame.getDefaultInstance() : frame_;
  }

  public static final int FIELD_FIELD_NUMBER = 3;
  private Protobuf.Field field_;
  /**
   * <code>.Protobuf.Field field = 3;</code>
   * @return Whether the field field is set.
   */
  @java.lang.Override
  public boolean hasField() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.Protobuf.Field field = 3;</code>
   * @return The field.
   */
  @java.lang.Override
  public Protobuf.Field getField() {
    return field_ == null ? Protobuf.Field.getDefaultInstance() : field_;
  }
  /**
   * <code>.Protobuf.Field field = 3;</code>
   */
  @java.lang.Override
  public Protobuf.FieldOrBuilder getFieldOrBuilder() {
    return field_ == null ? Protobuf.Field.getDefaultInstance() : field_;
  }

  public static final int GOALS_BLUE_FIELD_NUMBER = 4;
  private int goalsBlue_ = 0;
  /**
   * <code>uint32 goals_blue = 4;</code>
   * @return The goalsBlue.
   */
  @java.lang.Override
  public int getGoalsBlue() {
    return goalsBlue_;
  }

  public static final int GOALS_YELLOW_FIELD_NUMBER = 5;
  private int goalsYellow_ = 0;
  /**
   * <code>uint32 goals_yellow = 5;</code>
   * @return The goalsYellow.
   */
  @java.lang.Override
  public int getGoalsYellow() {
    return goalsYellow_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (step_ != 0) {
      output.writeUInt32(1, step_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getFrame());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getField());
    }
    if (goalsBlue_ != 0) {
      output.writeUInt32(4, goalsBlue_);
    }
    if (goalsYellow_ != 0) {
      output.writeUInt32(5, goalsYellow_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (step_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, step_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFrame());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getField());
    }
    if (goalsBlue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, goalsBlue_);
    }
    if (goalsYellow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, goalsYellow_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Protobuf.Environment)) {
      return super.equals(obj);
    }
    Protobuf.Environment other = (Protobuf.Environment) obj;

    if (getStep()
        != other.getStep()) return false;
    if (hasFrame() != other.hasFrame()) return false;
    if (hasFrame()) {
      if (!getFrame()
          .equals(other.getFrame())) return false;
    }
    if (hasField() != other.hasField()) return false;
    if (hasField()) {
      if (!getField()
          .equals(other.getField())) return false;
    }
    if (getGoalsBlue()
        != other.getGoalsBlue()) return false;
    if (getGoalsYellow()
        != other.getGoalsYellow()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STEP_FIELD_NUMBER;
    hash = (53 * hash) + getStep();
    if (hasFrame()) {
      hash = (37 * hash) + FRAME_FIELD_NUMBER;
      hash = (53 * hash) + getFrame().hashCode();
    }
    if (hasField()) {
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField().hashCode();
    }
    hash = (37 * hash) + GOALS_BLUE_FIELD_NUMBER;
    hash = (53 * hash) + getGoalsBlue();
    hash = (37 * hash) + GOALS_YELLOW_FIELD_NUMBER;
    hash = (53 * hash) + getGoalsYellow();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Protobuf.Environment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Environment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Environment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Environment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Environment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Environment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Environment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Environment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Protobuf.Environment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Protobuf.Environment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Protobuf.Environment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Environment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Protobuf.Environment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protobuf.Environment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protobuf.Environment)
      Protobuf.EnvironmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Environment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Environment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Environment.class, Protobuf.Environment.Builder.class);
    }

    // Construct using Protobuf.Environment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFrameFieldBuilder();
        getFieldFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      step_ = 0;
      frame_ = null;
      if (frameBuilder_ != null) {
        frameBuilder_.dispose();
        frameBuilder_ = null;
      }
      field_ = null;
      if (fieldBuilder_ != null) {
        fieldBuilder_.dispose();
        fieldBuilder_ = null;
      }
      goalsBlue_ = 0;
      goalsYellow_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Environment_descriptor;
    }

    @java.lang.Override
    public Protobuf.Environment getDefaultInstanceForType() {
      return Protobuf.Environment.getDefaultInstance();
    }

    @java.lang.Override
    public Protobuf.Environment build() {
      Protobuf.Environment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Protobuf.Environment buildPartial() {
      Protobuf.Environment result = new Protobuf.Environment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Protobuf.Environment result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.step_ = step_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.frame_ = frameBuilder_ == null
            ? frame_
            : frameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.field_ = fieldBuilder_ == null
            ? field_
            : fieldBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.goalsBlue_ = goalsBlue_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.goalsYellow_ = goalsYellow_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Protobuf.Environment) {
        return mergeFrom((Protobuf.Environment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Protobuf.Environment other) {
      if (other == Protobuf.Environment.getDefaultInstance()) return this;
      if (other.getStep() != 0) {
        setStep(other.getStep());
      }
      if (other.hasFrame()) {
        mergeFrame(other.getFrame());
      }
      if (other.hasField()) {
        mergeField(other.getField());
      }
      if (other.getGoalsBlue() != 0) {
        setGoalsBlue(other.getGoalsBlue());
      }
      if (other.getGoalsYellow() != 0) {
        setGoalsYellow(other.getGoalsYellow());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              step_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getFrameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getFieldFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              goalsBlue_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              goalsYellow_ = input.readUInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int step_ ;
    /**
     * <code>uint32 step = 1;</code>
     * @return The step.
     */
    @java.lang.Override
    public int getStep() {
      return step_;
    }
    /**
     * <code>uint32 step = 1;</code>
     * @param value The step to set.
     * @return This builder for chaining.
     */
    public Builder setStep(int value) {

      step_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 step = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStep() {
      bitField0_ = (bitField0_ & ~0x00000001);
      step_ = 0;
      onChanged();
      return this;
    }

    private Protobuf.Frame frame_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Frame, Protobuf.Frame.Builder, Protobuf.FrameOrBuilder> frameBuilder_;
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     * @return Whether the frame field is set.
     */
    public boolean hasFrame() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     * @return The frame.
     */
    public Protobuf.Frame getFrame() {
      if (frameBuilder_ == null) {
        return frame_ == null ? Protobuf.Frame.getDefaultInstance() : frame_;
      } else {
        return frameBuilder_.getMessage();
      }
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Builder setFrame(Protobuf.Frame value) {
      if (frameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        frame_ = value;
      } else {
        frameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Builder setFrame(
        Protobuf.Frame.Builder builderForValue) {
      if (frameBuilder_ == null) {
        frame_ = builderForValue.build();
      } else {
        frameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Builder mergeFrame(Protobuf.Frame value) {
      if (frameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          frame_ != null &&
          frame_ != Protobuf.Frame.getDefaultInstance()) {
          getFrameBuilder().mergeFrom(value);
        } else {
          frame_ = value;
        }
      } else {
        frameBuilder_.mergeFrom(value);
      }
      if (frame_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Builder clearFrame() {
      bitField0_ = (bitField0_ & ~0x00000002);
      frame_ = null;
      if (frameBuilder_ != null) {
        frameBuilder_.dispose();
        frameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Protobuf.Frame.Builder getFrameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFrameFieldBuilder().getBuilder();
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    public Protobuf.FrameOrBuilder getFrameOrBuilder() {
      if (frameBuilder_ != null) {
        return frameBuilder_.getMessageOrBuilder();
      } else {
        return frame_ == null ?
            Protobuf.Frame.getDefaultInstance() : frame_;
      }
    }
    /**
     * <code>.Protobuf.Frame frame = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Frame, Protobuf.Frame.Builder, Protobuf.FrameOrBuilder> 
        getFrameFieldBuilder() {
      if (frameBuilder_ == null) {
        frameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Protobuf.Frame, Protobuf.Frame.Builder, Protobuf.FrameOrBuilder>(
                getFrame(),
                getParentForChildren(),
                isClean());
        frame_ = null;
      }
      return frameBuilder_;
    }

    private Protobuf.Field field_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Field, Protobuf.Field.Builder, Protobuf.FieldOrBuilder> fieldBuilder_;
    /**
     * <code>.Protobuf.Field field = 3;</code>
     * @return Whether the field field is set.
     */
    public boolean hasField() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     * @return The field.
     */
    public Protobuf.Field getField() {
      if (fieldBuilder_ == null) {
        return field_ == null ? Protobuf.Field.getDefaultInstance() : field_;
      } else {
        return fieldBuilder_.getMessage();
      }
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Builder setField(Protobuf.Field value) {
      if (fieldBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        field_ = value;
      } else {
        fieldBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Builder setField(
        Protobuf.Field.Builder builderForValue) {
      if (fieldBuilder_ == null) {
        field_ = builderForValue.build();
      } else {
        fieldBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Builder mergeField(Protobuf.Field value) {
      if (fieldBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          field_ != null &&
          field_ != Protobuf.Field.getDefaultInstance()) {
          getFieldBuilder().mergeFrom(value);
        } else {
          field_ = value;
        }
      } else {
        fieldBuilder_.mergeFrom(value);
      }
      if (field_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Builder clearField() {
      bitField0_ = (bitField0_ & ~0x00000004);
      field_ = null;
      if (fieldBuilder_ != null) {
        fieldBuilder_.dispose();
        fieldBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Protobuf.Field.Builder getFieldBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getFieldFieldBuilder().getBuilder();
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    public Protobuf.FieldOrBuilder getFieldOrBuilder() {
      if (fieldBuilder_ != null) {
        return fieldBuilder_.getMessageOrBuilder();
      } else {
        return field_ == null ?
            Protobuf.Field.getDefaultInstance() : field_;
      }
    }
    /**
     * <code>.Protobuf.Field field = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Field, Protobuf.Field.Builder, Protobuf.FieldOrBuilder> 
        getFieldFieldBuilder() {
      if (fieldBuilder_ == null) {
        fieldBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Protobuf.Field, Protobuf.Field.Builder, Protobuf.FieldOrBuilder>(
                getField(),
                getParentForChildren(),
                isClean());
        field_ = null;
      }
      return fieldBuilder_;
    }

    private int goalsBlue_ ;
    /**
     * <code>uint32 goals_blue = 4;</code>
     * @return The goalsBlue.
     */
    @java.lang.Override
    public int getGoalsBlue() {
      return goalsBlue_;
    }
    /**
     * <code>uint32 goals_blue = 4;</code>
     * @param value The goalsBlue to set.
     * @return This builder for chaining.
     */
    public Builder setGoalsBlue(int value) {

      goalsBlue_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 goals_blue = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoalsBlue() {
      bitField0_ = (bitField0_ & ~0x00000008);
      goalsBlue_ = 0;
      onChanged();
      return this;
    }

    private int goalsYellow_ ;
    /**
     * <code>uint32 goals_yellow = 5;</code>
     * @return The goalsYellow.
     */
    @java.lang.Override
    public int getGoalsYellow() {
      return goalsYellow_;
    }
    /**
     * <code>uint32 goals_yellow = 5;</code>
     * @param value The goalsYellow to set.
     * @return This builder for chaining.
     */
    public Builder setGoalsYellow(int value) {

      goalsYellow_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 goals_yellow = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoalsYellow() {
      bitField0_ = (bitField0_ & ~0x00000010);
      goalsYellow_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protobuf.Environment)
  }

  // @@protoc_insertion_point(class_scope:Protobuf.Environment)
  private static final Protobuf.Environment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Protobuf.Environment();
  }

  public static Protobuf.Environment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Environment>
      PARSER = new com.google.protobuf.AbstractParser<Environment>() {
    @java.lang.Override
    public Environment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Environment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Environment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Protobuf.Environment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

