// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public interface FieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protobuf.Field)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double width = 1;</code>
   * @return The width.
   */
  double getWidth();

  /**
   * <code>double length = 2;</code>
   * @return The length.
   */
  double getLength();

  /**
   * <code>double goal_width = 3;</code>
   * @return The goalWidth.
   */
  double getGoalWidth();

  /**
   * <code>double goal_depth = 4;</code>
   * @return The goalDepth.
   */
  double getGoalDepth();
}
