// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

/**
 * Protobuf type {@code Protobuf.Field}
 */
public final class Field extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protobuf.Field)
    FieldOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Field.newBuilder() to construct.
  private Field(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Field() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Field();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Field_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Field_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Protobuf.Field.class, Protobuf.Field.Builder.class);
  }

  public static final int WIDTH_FIELD_NUMBER = 1;
  private double width_ = 0D;
  /**
   * <code>double width = 1;</code>
   * @return The width.
   */
  @java.lang.Override
  public double getWidth() {
    return width_;
  }

  public static final int LENGTH_FIELD_NUMBER = 2;
  private double length_ = 0D;
  /**
   * <code>double length = 2;</code>
   * @return The length.
   */
  @java.lang.Override
  public double getLength() {
    return length_;
  }

  public static final int GOAL_WIDTH_FIELD_NUMBER = 3;
  private double goalWidth_ = 0D;
  /**
   * <code>double goal_width = 3;</code>
   * @return The goalWidth.
   */
  @java.lang.Override
  public double getGoalWidth() {
    return goalWidth_;
  }

  public static final int GOAL_DEPTH_FIELD_NUMBER = 4;
  private double goalDepth_ = 0D;
  /**
   * <code>double goal_depth = 4;</code>
   * @return The goalDepth.
   */
  @java.lang.Override
  public double getGoalDepth() {
    return goalDepth_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(width_) != 0) {
      output.writeDouble(1, width_);
    }
    if (java.lang.Double.doubleToRawLongBits(length_) != 0) {
      output.writeDouble(2, length_);
    }
    if (java.lang.Double.doubleToRawLongBits(goalWidth_) != 0) {
      output.writeDouble(3, goalWidth_);
    }
    if (java.lang.Double.doubleToRawLongBits(goalDepth_) != 0) {
      output.writeDouble(4, goalDepth_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(width_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, width_);
    }
    if (java.lang.Double.doubleToRawLongBits(length_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, length_);
    }
    if (java.lang.Double.doubleToRawLongBits(goalWidth_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, goalWidth_);
    }
    if (java.lang.Double.doubleToRawLongBits(goalDepth_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, goalDepth_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Protobuf.Field)) {
      return super.equals(obj);
    }
    Protobuf.Field other = (Protobuf.Field) obj;

    if (java.lang.Double.doubleToLongBits(getWidth())
        != java.lang.Double.doubleToLongBits(
            other.getWidth())) return false;
    if (java.lang.Double.doubleToLongBits(getLength())
        != java.lang.Double.doubleToLongBits(
            other.getLength())) return false;
    if (java.lang.Double.doubleToLongBits(getGoalWidth())
        != java.lang.Double.doubleToLongBits(
            other.getGoalWidth())) return false;
    if (java.lang.Double.doubleToLongBits(getGoalDepth())
        != java.lang.Double.doubleToLongBits(
            other.getGoalDepth())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWidth()));
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLength()));
    hash = (37 * hash) + GOAL_WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getGoalWidth()));
    hash = (37 * hash) + GOAL_DEPTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getGoalDepth()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Protobuf.Field parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Field parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Field parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Field parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Field parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Field parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Field parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Field parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Protobuf.Field parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Protobuf.Field parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Field parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Protobuf.Field prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protobuf.Field}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protobuf.Field)
      Protobuf.FieldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Field_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Field_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Field.class, Protobuf.Field.Builder.class);
    }

    // Construct using Protobuf.Field.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      width_ = 0D;
      length_ = 0D;
      goalWidth_ = 0D;
      goalDepth_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Field_descriptor;
    }

    @java.lang.Override
    public Protobuf.Field getDefaultInstanceForType() {
      return Protobuf.Field.getDefaultInstance();
    }

    @java.lang.Override
    public Protobuf.Field build() {
      Protobuf.Field result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Protobuf.Field buildPartial() {
      Protobuf.Field result = new Protobuf.Field(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Protobuf.Field result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.width_ = width_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.length_ = length_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.goalWidth_ = goalWidth_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.goalDepth_ = goalDepth_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Protobuf.Field) {
        return mergeFrom((Protobuf.Field)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Protobuf.Field other) {
      if (other == Protobuf.Field.getDefaultInstance()) return this;
      if (other.getWidth() != 0D) {
        setWidth(other.getWidth());
      }
      if (other.getLength() != 0D) {
        setLength(other.getLength());
      }
      if (other.getGoalWidth() != 0D) {
        setGoalWidth(other.getGoalWidth());
      }
      if (other.getGoalDepth() != 0D) {
        setGoalDepth(other.getGoalDepth());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              width_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              length_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              goalWidth_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              goalDepth_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double width_ ;
    /**
     * <code>double width = 1;</code>
     * @return The width.
     */
    @java.lang.Override
    public double getWidth() {
      return width_;
    }
    /**
     * <code>double width = 1;</code>
     * @param value The width to set.
     * @return This builder for chaining.
     */
    public Builder setWidth(double value) {

      width_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double width = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWidth() {
      bitField0_ = (bitField0_ & ~0x00000001);
      width_ = 0D;
      onChanged();
      return this;
    }

    private double length_ ;
    /**
     * <code>double length = 2;</code>
     * @return The length.
     */
    @java.lang.Override
    public double getLength() {
      return length_;
    }
    /**
     * <code>double length = 2;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(double value) {

      length_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double length = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000002);
      length_ = 0D;
      onChanged();
      return this;
    }

    private double goalWidth_ ;
    /**
     * <code>double goal_width = 3;</code>
     * @return The goalWidth.
     */
    @java.lang.Override
    public double getGoalWidth() {
      return goalWidth_;
    }
    /**
     * <code>double goal_width = 3;</code>
     * @param value The goalWidth to set.
     * @return This builder for chaining.
     */
    public Builder setGoalWidth(double value) {

      goalWidth_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double goal_width = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoalWidth() {
      bitField0_ = (bitField0_ & ~0x00000004);
      goalWidth_ = 0D;
      onChanged();
      return this;
    }

    private double goalDepth_ ;
    /**
     * <code>double goal_depth = 4;</code>
     * @return The goalDepth.
     */
    @java.lang.Override
    public double getGoalDepth() {
      return goalDepth_;
    }
    /**
     * <code>double goal_depth = 4;</code>
     * @param value The goalDepth to set.
     * @return This builder for chaining.
     */
    public Builder setGoalDepth(double value) {

      goalDepth_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double goal_depth = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoalDepth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      goalDepth_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protobuf.Field)
  }

  // @@protoc_insertion_point(class_scope:Protobuf.Field)
  private static final Protobuf.Field DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Protobuf.Field();
  }

  public static Protobuf.Field getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Field>
      PARSER = new com.google.protobuf.AbstractParser<Field>() {
    @java.lang.Override
    public Field parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Field> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Field> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Protobuf.Field getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

