// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public final class FIRASimVisionMessage {
  private FIRASimVisionMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Ball_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_Ball_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Robot_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_Robot_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_Field_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Frame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_Frame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Protobuf_Environment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Protobuf_Environment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032FIRASimVisionMessage.proto\022\010Protobuf\"K" +
      "\n\004Ball\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z\030\003 \001(\001\022" +
      "\n\n\002vx\030\004 \001(\001\022\n\n\002vy\030\005 \001(\001\022\n\n\002vz\030\006 \001(\001\"r\n\005R" +
      "obot\022\020\n\010robot_id\030\001 \001(\r\022\t\n\001x\030\002 \001(\001\022\t\n\001y\030\003" +
      " \001(\001\022\023\n\013orientation\030\004 \001(\001\022\n\n\002vx\030\005 \001(\001\022\n\n" +
      "\002vy\030\006 \001(\001\022\024\n\014vorientation\030\007 \001(\001\"N\n\005Field" +
      "\022\r\n\005width\030\001 \001(\001\022\016\n\006length\030\002 \001(\001\022\022\n\ngoal_" +
      "width\030\003 \001(\001\022\022\n\ngoal_depth\030\004 \001(\001\"s\n\005Frame" +
      "\022\034\n\004ball\030\001 \001(\0132\016.Protobuf.Ball\022&\n\rrobots" +
      "_yellow\030\002 \003(\0132\017.Protobuf.Robot\022$\n\013robots" +
      "_blue\030\003 \003(\0132\017.Protobuf.Robot\"\205\001\n\013Environ" +
      "ment\022\014\n\004step\030\001 \001(\r\022\036\n\005frame\030\002 \001(\0132\017.Prot" +
      "obuf.Frame\022\036\n\005field\030\003 \001(\0132\017.Protobuf.Fie" +
      "ld\022\022\n\ngoals_blue\030\004 \001(\r\022\024\n\014goals_yellow\030\005" +
      " \001(\rB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Protobuf_Ball_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Protobuf_Ball_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_Ball_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "Vx", "Vy", "Vz", });
    internal_static_Protobuf_Robot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Protobuf_Robot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_Robot_descriptor,
        new java.lang.String[] { "RobotId", "X", "Y", "Orientation", "Vx", "Vy", "Vorientation", });
    internal_static_Protobuf_Field_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Protobuf_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_Field_descriptor,
        new java.lang.String[] { "Width", "Length", "GoalWidth", "GoalDepth", });
    internal_static_Protobuf_Frame_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Protobuf_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_Frame_descriptor,
        new java.lang.String[] { "Ball", "RobotsYellow", "RobotsBlue", });
    internal_static_Protobuf_Environment_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Protobuf_Environment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Protobuf_Environment_descriptor,
        new java.lang.String[] { "Step", "Frame", "Field", "GoalsBlue", "GoalsYellow", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
