// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protobuf.Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   * @return Whether the ball field is set.
   */
  boolean hasBall();
  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   * @return The ball.
   */
  Protobuf.Ball getBall();
  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   */
  Protobuf.BallOrBuilder getBallOrBuilder();

  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  java.util.List<Protobuf.Robot> 
      getRobotsYellowList();
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  Protobuf.Robot getRobotsYellow(int index);
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  int getRobotsYellowCount();
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  java.util.List<? extends Protobuf.RobotOrBuilder> 
      getRobotsYellowOrBuilderList();
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  Protobuf.RobotOrBuilder getRobotsYellowOrBuilder(
      int index);

  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  java.util.List<Protobuf.Robot> 
      getRobotsBlueList();
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  Protobuf.Robot getRobotsBlue(int index);
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  int getRobotsBlueCount();
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  java.util.List<? extends Protobuf.RobotOrBuilder> 
      getRobotsBlueOrBuilderList();
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  Protobuf.RobotOrBuilder getRobotsBlueOrBuilder(
      int index);
}
