// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

/**
 * Protobuf type {@code Protobuf.Frame}
 */
public final class Frame extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protobuf.Frame)
    FrameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Frame.newBuilder() to construct.
  private Frame(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Frame() {
    robotsYellow_ = java.util.Collections.emptyList();
    robotsBlue_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Frame();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Frame_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Frame_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Protobuf.Frame.class, Protobuf.Frame.Builder.class);
  }

  private int bitField0_;
  public static final int BALL_FIELD_NUMBER = 1;
  private Protobuf.Ball ball_;
  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   * @return Whether the ball field is set.
   */
  @java.lang.Override
  public boolean hasBall() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   * @return The ball.
   */
  @java.lang.Override
  public Protobuf.Ball getBall() {
    return ball_ == null ? Protobuf.Ball.getDefaultInstance() : ball_;
  }
  /**
   * <code>.Protobuf.Ball ball = 1;</code>
   */
  @java.lang.Override
  public Protobuf.BallOrBuilder getBallOrBuilder() {
    return ball_ == null ? Protobuf.Ball.getDefaultInstance() : ball_;
  }

  public static final int ROBOTS_YELLOW_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<Protobuf.Robot> robotsYellow_;
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  @java.lang.Override
  public java.util.List<Protobuf.Robot> getRobotsYellowList() {
    return robotsYellow_;
  }
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends Protobuf.RobotOrBuilder> 
      getRobotsYellowOrBuilderList() {
    return robotsYellow_;
  }
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  @java.lang.Override
  public int getRobotsYellowCount() {
    return robotsYellow_.size();
  }
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  @java.lang.Override
  public Protobuf.Robot getRobotsYellow(int index) {
    return robotsYellow_.get(index);
  }
  /**
   * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
   */
  @java.lang.Override
  public Protobuf.RobotOrBuilder getRobotsYellowOrBuilder(
      int index) {
    return robotsYellow_.get(index);
  }

  public static final int ROBOTS_BLUE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<Protobuf.Robot> robotsBlue_;
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  @java.lang.Override
  public java.util.List<Protobuf.Robot> getRobotsBlueList() {
    return robotsBlue_;
  }
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends Protobuf.RobotOrBuilder> 
      getRobotsBlueOrBuilderList() {
    return robotsBlue_;
  }
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  @java.lang.Override
  public int getRobotsBlueCount() {
    return robotsBlue_.size();
  }
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  @java.lang.Override
  public Protobuf.Robot getRobotsBlue(int index) {
    return robotsBlue_.get(index);
  }
  /**
   * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
   */
  @java.lang.Override
  public Protobuf.RobotOrBuilder getRobotsBlueOrBuilder(
      int index) {
    return robotsBlue_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getBall());
    }
    for (int i = 0; i < robotsYellow_.size(); i++) {
      output.writeMessage(2, robotsYellow_.get(i));
    }
    for (int i = 0; i < robotsBlue_.size(); i++) {
      output.writeMessage(3, robotsBlue_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBall());
    }
    for (int i = 0; i < robotsYellow_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, robotsYellow_.get(i));
    }
    for (int i = 0; i < robotsBlue_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, robotsBlue_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Protobuf.Frame)) {
      return super.equals(obj);
    }
    Protobuf.Frame other = (Protobuf.Frame) obj;

    if (hasBall() != other.hasBall()) return false;
    if (hasBall()) {
      if (!getBall()
          .equals(other.getBall())) return false;
    }
    if (!getRobotsYellowList()
        .equals(other.getRobotsYellowList())) return false;
    if (!getRobotsBlueList()
        .equals(other.getRobotsBlueList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBall()) {
      hash = (37 * hash) + BALL_FIELD_NUMBER;
      hash = (53 * hash) + getBall().hashCode();
    }
    if (getRobotsYellowCount() > 0) {
      hash = (37 * hash) + ROBOTS_YELLOW_FIELD_NUMBER;
      hash = (53 * hash) + getRobotsYellowList().hashCode();
    }
    if (getRobotsBlueCount() > 0) {
      hash = (37 * hash) + ROBOTS_BLUE_FIELD_NUMBER;
      hash = (53 * hash) + getRobotsBlueList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Protobuf.Frame parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Frame parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Frame parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Frame parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Frame parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Frame parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Frame parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Frame parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Protobuf.Frame parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Protobuf.Frame parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Protobuf.Frame parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Frame parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Protobuf.Frame prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protobuf.Frame}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protobuf.Frame)
      Protobuf.FrameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Frame_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Frame.class, Protobuf.Frame.Builder.class);
    }

    // Construct using Protobuf.Frame.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBallFieldBuilder();
        getRobotsYellowFieldBuilder();
        getRobotsBlueFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      ball_ = null;
      if (ballBuilder_ != null) {
        ballBuilder_.dispose();
        ballBuilder_ = null;
      }
      if (robotsYellowBuilder_ == null) {
        robotsYellow_ = java.util.Collections.emptyList();
      } else {
        robotsYellow_ = null;
        robotsYellowBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (robotsBlueBuilder_ == null) {
        robotsBlue_ = java.util.Collections.emptyList();
      } else {
        robotsBlue_ = null;
        robotsBlueBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Frame_descriptor;
    }

    @java.lang.Override
    public Protobuf.Frame getDefaultInstanceForType() {
      return Protobuf.Frame.getDefaultInstance();
    }

    @java.lang.Override
    public Protobuf.Frame build() {
      Protobuf.Frame result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Protobuf.Frame buildPartial() {
      Protobuf.Frame result = new Protobuf.Frame(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(Protobuf.Frame result) {
      if (robotsYellowBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          robotsYellow_ = java.util.Collections.unmodifiableList(robotsYellow_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.robotsYellow_ = robotsYellow_;
      } else {
        result.robotsYellow_ = robotsYellowBuilder_.build();
      }
      if (robotsBlueBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          robotsBlue_ = java.util.Collections.unmodifiableList(robotsBlue_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.robotsBlue_ = robotsBlue_;
      } else {
        result.robotsBlue_ = robotsBlueBuilder_.build();
      }
    }

    private void buildPartial0(Protobuf.Frame result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.ball_ = ballBuilder_ == null
            ? ball_
            : ballBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Protobuf.Frame) {
        return mergeFrom((Protobuf.Frame)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Protobuf.Frame other) {
      if (other == Protobuf.Frame.getDefaultInstance()) return this;
      if (other.hasBall()) {
        mergeBall(other.getBall());
      }
      if (robotsYellowBuilder_ == null) {
        if (!other.robotsYellow_.isEmpty()) {
          if (robotsYellow_.isEmpty()) {
            robotsYellow_ = other.robotsYellow_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureRobotsYellowIsMutable();
            robotsYellow_.addAll(other.robotsYellow_);
          }
          onChanged();
        }
      } else {
        if (!other.robotsYellow_.isEmpty()) {
          if (robotsYellowBuilder_.isEmpty()) {
            robotsYellowBuilder_.dispose();
            robotsYellowBuilder_ = null;
            robotsYellow_ = other.robotsYellow_;
            bitField0_ = (bitField0_ & ~0x00000002);
            robotsYellowBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRobotsYellowFieldBuilder() : null;
          } else {
            robotsYellowBuilder_.addAllMessages(other.robotsYellow_);
          }
        }
      }
      if (robotsBlueBuilder_ == null) {
        if (!other.robotsBlue_.isEmpty()) {
          if (robotsBlue_.isEmpty()) {
            robotsBlue_ = other.robotsBlue_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureRobotsBlueIsMutable();
            robotsBlue_.addAll(other.robotsBlue_);
          }
          onChanged();
        }
      } else {
        if (!other.robotsBlue_.isEmpty()) {
          if (robotsBlueBuilder_.isEmpty()) {
            robotsBlueBuilder_.dispose();
            robotsBlueBuilder_ = null;
            robotsBlue_ = other.robotsBlue_;
            bitField0_ = (bitField0_ & ~0x00000004);
            robotsBlueBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRobotsBlueFieldBuilder() : null;
          } else {
            robotsBlueBuilder_.addAllMessages(other.robotsBlue_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getBallFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              Protobuf.Robot m =
                  input.readMessage(
                      Protobuf.Robot.parser(),
                      extensionRegistry);
              if (robotsYellowBuilder_ == null) {
                ensureRobotsYellowIsMutable();
                robotsYellow_.add(m);
              } else {
                robotsYellowBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              Protobuf.Robot m =
                  input.readMessage(
                      Protobuf.Robot.parser(),
                      extensionRegistry);
              if (robotsBlueBuilder_ == null) {
                ensureRobotsBlueIsMutable();
                robotsBlue_.add(m);
              } else {
                robotsBlueBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Protobuf.Ball ball_;
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Ball, Protobuf.Ball.Builder, Protobuf.BallOrBuilder> ballBuilder_;
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     * @return Whether the ball field is set.
     */
    public boolean hasBall() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     * @return The ball.
     */
    public Protobuf.Ball getBall() {
      if (ballBuilder_ == null) {
        return ball_ == null ? Protobuf.Ball.getDefaultInstance() : ball_;
      } else {
        return ballBuilder_.getMessage();
      }
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Builder setBall(Protobuf.Ball value) {
      if (ballBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ball_ = value;
      } else {
        ballBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Builder setBall(
        Protobuf.Ball.Builder builderForValue) {
      if (ballBuilder_ == null) {
        ball_ = builderForValue.build();
      } else {
        ballBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Builder mergeBall(Protobuf.Ball value) {
      if (ballBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          ball_ != null &&
          ball_ != Protobuf.Ball.getDefaultInstance()) {
          getBallBuilder().mergeFrom(value);
        } else {
          ball_ = value;
        }
      } else {
        ballBuilder_.mergeFrom(value);
      }
      if (ball_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Builder clearBall() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ball_ = null;
      if (ballBuilder_ != null) {
        ballBuilder_.dispose();
        ballBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Protobuf.Ball.Builder getBallBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getBallFieldBuilder().getBuilder();
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    public Protobuf.BallOrBuilder getBallOrBuilder() {
      if (ballBuilder_ != null) {
        return ballBuilder_.getMessageOrBuilder();
      } else {
        return ball_ == null ?
            Protobuf.Ball.getDefaultInstance() : ball_;
      }
    }
    /**
     * <code>.Protobuf.Ball ball = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Protobuf.Ball, Protobuf.Ball.Builder, Protobuf.BallOrBuilder> 
        getBallFieldBuilder() {
      if (ballBuilder_ == null) {
        ballBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Protobuf.Ball, Protobuf.Ball.Builder, Protobuf.BallOrBuilder>(
                getBall(),
                getParentForChildren(),
                isClean());
        ball_ = null;
      }
      return ballBuilder_;
    }

    private java.util.List<Protobuf.Robot> robotsYellow_ =
      java.util.Collections.emptyList();
    private void ensureRobotsYellowIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        robotsYellow_ = new java.util.ArrayList<Protobuf.Robot>(robotsYellow_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder> robotsYellowBuilder_;

    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public java.util.List<Protobuf.Robot> getRobotsYellowList() {
      if (robotsYellowBuilder_ == null) {
        return java.util.Collections.unmodifiableList(robotsYellow_);
      } else {
        return robotsYellowBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public int getRobotsYellowCount() {
      if (robotsYellowBuilder_ == null) {
        return robotsYellow_.size();
      } else {
        return robotsYellowBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Protobuf.Robot getRobotsYellow(int index) {
      if (robotsYellowBuilder_ == null) {
        return robotsYellow_.get(index);
      } else {
        return robotsYellowBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder setRobotsYellow(
        int index, Protobuf.Robot value) {
      if (robotsYellowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsYellowIsMutable();
        robotsYellow_.set(index, value);
        onChanged();
      } else {
        robotsYellowBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder setRobotsYellow(
        int index, Protobuf.Robot.Builder builderForValue) {
      if (robotsYellowBuilder_ == null) {
        ensureRobotsYellowIsMutable();
        robotsYellow_.set(index, builderForValue.build());
        onChanged();
      } else {
        robotsYellowBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder addRobotsYellow(Protobuf.Robot value) {
      if (robotsYellowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsYellowIsMutable();
        robotsYellow_.add(value);
        onChanged();
      } else {
        robotsYellowBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder addRobotsYellow(
        int index, Protobuf.Robot value) {
      if (robotsYellowBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsYellowIsMutable();
        robotsYellow_.add(index, value);
        onChanged();
      } else {
        robotsYellowBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder addRobotsYellow(
        Protobuf.Robot.Builder builderForValue) {
      if (robotsYellowBuilder_ == null) {
        ensureRobotsYellowIsMutable();
        robotsYellow_.add(builderForValue.build());
        onChanged();
      } else {
        robotsYellowBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder addRobotsYellow(
        int index, Protobuf.Robot.Builder builderForValue) {
      if (robotsYellowBuilder_ == null) {
        ensureRobotsYellowIsMutable();
        robotsYellow_.add(index, builderForValue.build());
        onChanged();
      } else {
        robotsYellowBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder addAllRobotsYellow(
        java.lang.Iterable<? extends Protobuf.Robot> values) {
      if (robotsYellowBuilder_ == null) {
        ensureRobotsYellowIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, robotsYellow_);
        onChanged();
      } else {
        robotsYellowBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder clearRobotsYellow() {
      if (robotsYellowBuilder_ == null) {
        robotsYellow_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        robotsYellowBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Builder removeRobotsYellow(int index) {
      if (robotsYellowBuilder_ == null) {
        ensureRobotsYellowIsMutable();
        robotsYellow_.remove(index);
        onChanged();
      } else {
        robotsYellowBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Protobuf.Robot.Builder getRobotsYellowBuilder(
        int index) {
      return getRobotsYellowFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Protobuf.RobotOrBuilder getRobotsYellowOrBuilder(
        int index) {
      if (robotsYellowBuilder_ == null) {
        return robotsYellow_.get(index);  } else {
        return robotsYellowBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public java.util.List<? extends Protobuf.RobotOrBuilder> 
         getRobotsYellowOrBuilderList() {
      if (robotsYellowBuilder_ != null) {
        return robotsYellowBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(robotsYellow_);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Protobuf.Robot.Builder addRobotsYellowBuilder() {
      return getRobotsYellowFieldBuilder().addBuilder(
          Protobuf.Robot.getDefaultInstance());
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public Protobuf.Robot.Builder addRobotsYellowBuilder(
        int index) {
      return getRobotsYellowFieldBuilder().addBuilder(
          index, Protobuf.Robot.getDefaultInstance());
    }
    /**
     * <code>repeated .Protobuf.Robot robots_yellow = 2;</code>
     */
    public java.util.List<Protobuf.Robot.Builder> 
         getRobotsYellowBuilderList() {
      return getRobotsYellowFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder> 
        getRobotsYellowFieldBuilder() {
      if (robotsYellowBuilder_ == null) {
        robotsYellowBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder>(
                robotsYellow_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        robotsYellow_ = null;
      }
      return robotsYellowBuilder_;
    }

    private java.util.List<Protobuf.Robot> robotsBlue_ =
      java.util.Collections.emptyList();
    private void ensureRobotsBlueIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        robotsBlue_ = new java.util.ArrayList<Protobuf.Robot>(robotsBlue_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder> robotsBlueBuilder_;

    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public java.util.List<Protobuf.Robot> getRobotsBlueList() {
      if (robotsBlueBuilder_ == null) {
        return java.util.Collections.unmodifiableList(robotsBlue_);
      } else {
        return robotsBlueBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public int getRobotsBlueCount() {
      if (robotsBlueBuilder_ == null) {
        return robotsBlue_.size();
      } else {
        return robotsBlueBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Protobuf.Robot getRobotsBlue(int index) {
      if (robotsBlueBuilder_ == null) {
        return robotsBlue_.get(index);
      } else {
        return robotsBlueBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder setRobotsBlue(
        int index, Protobuf.Robot value) {
      if (robotsBlueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsBlueIsMutable();
        robotsBlue_.set(index, value);
        onChanged();
      } else {
        robotsBlueBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder setRobotsBlue(
        int index, Protobuf.Robot.Builder builderForValue) {
      if (robotsBlueBuilder_ == null) {
        ensureRobotsBlueIsMutable();
        robotsBlue_.set(index, builderForValue.build());
        onChanged();
      } else {
        robotsBlueBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder addRobotsBlue(Protobuf.Robot value) {
      if (robotsBlueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsBlueIsMutable();
        robotsBlue_.add(value);
        onChanged();
      } else {
        robotsBlueBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder addRobotsBlue(
        int index, Protobuf.Robot value) {
      if (robotsBlueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRobotsBlueIsMutable();
        robotsBlue_.add(index, value);
        onChanged();
      } else {
        robotsBlueBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder addRobotsBlue(
        Protobuf.Robot.Builder builderForValue) {
      if (robotsBlueBuilder_ == null) {
        ensureRobotsBlueIsMutable();
        robotsBlue_.add(builderForValue.build());
        onChanged();
      } else {
        robotsBlueBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder addRobotsBlue(
        int index, Protobuf.Robot.Builder builderForValue) {
      if (robotsBlueBuilder_ == null) {
        ensureRobotsBlueIsMutable();
        robotsBlue_.add(index, builderForValue.build());
        onChanged();
      } else {
        robotsBlueBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder addAllRobotsBlue(
        java.lang.Iterable<? extends Protobuf.Robot> values) {
      if (robotsBlueBuilder_ == null) {
        ensureRobotsBlueIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, robotsBlue_);
        onChanged();
      } else {
        robotsBlueBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder clearRobotsBlue() {
      if (robotsBlueBuilder_ == null) {
        robotsBlue_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        robotsBlueBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Builder removeRobotsBlue(int index) {
      if (robotsBlueBuilder_ == null) {
        ensureRobotsBlueIsMutable();
        robotsBlue_.remove(index);
        onChanged();
      } else {
        robotsBlueBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Protobuf.Robot.Builder getRobotsBlueBuilder(
        int index) {
      return getRobotsBlueFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Protobuf.RobotOrBuilder getRobotsBlueOrBuilder(
        int index) {
      if (robotsBlueBuilder_ == null) {
        return robotsBlue_.get(index);  } else {
        return robotsBlueBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public java.util.List<? extends Protobuf.RobotOrBuilder> 
         getRobotsBlueOrBuilderList() {
      if (robotsBlueBuilder_ != null) {
        return robotsBlueBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(robotsBlue_);
      }
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Protobuf.Robot.Builder addRobotsBlueBuilder() {
      return getRobotsBlueFieldBuilder().addBuilder(
          Protobuf.Robot.getDefaultInstance());
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public Protobuf.Robot.Builder addRobotsBlueBuilder(
        int index) {
      return getRobotsBlueFieldBuilder().addBuilder(
          index, Protobuf.Robot.getDefaultInstance());
    }
    /**
     * <code>repeated .Protobuf.Robot robots_blue = 3;</code>
     */
    public java.util.List<Protobuf.Robot.Builder> 
         getRobotsBlueBuilderList() {
      return getRobotsBlueFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder> 
        getRobotsBlueFieldBuilder() {
      if (robotsBlueBuilder_ == null) {
        robotsBlueBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Protobuf.Robot, Protobuf.Robot.Builder, Protobuf.RobotOrBuilder>(
                robotsBlue_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        robotsBlue_ = null;
      }
      return robotsBlueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protobuf.Frame)
  }

  // @@protoc_insertion_point(class_scope:Protobuf.Frame)
  private static final Protobuf.Frame DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Protobuf.Frame();
  }

  public static Protobuf.Frame getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Frame>
      PARSER = new com.google.protobuf.AbstractParser<Frame>() {
    @java.lang.Override
    public Frame parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Frame> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Frame> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Protobuf.Frame getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

