// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

/**
 * Protobuf type {@code Protobuf.Robot}
 */
public final class Robot extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Protobuf.Robot)
    RobotOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Robot.newBuilder() to construct.
  private Robot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Robot() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Robot();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Robot_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Robot_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Protobuf.Robot.class, Protobuf.Robot.Builder.class);
  }

  public static final int ROBOT_ID_FIELD_NUMBER = 1;
  private int robotId_ = 0;
  /**
   * <code>uint32 robot_id = 1;</code>
   * @return The robotId.
   */
  @java.lang.Override
  public int getRobotId() {
    return robotId_;
  }

  public static final int X_FIELD_NUMBER = 2;
  private double x_ = 0D;
  /**
   * <code>double x = 2;</code>
   * @return The x.
   */
  @java.lang.Override
  public double getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 3;
  private double y_ = 0D;
  /**
   * <code>double y = 3;</code>
   * @return The y.
   */
  @java.lang.Override
  public double getY() {
    return y_;
  }

  public static final int ORIENTATION_FIELD_NUMBER = 4;
  private double orientation_ = 0D;
  /**
   * <code>double orientation = 4;</code>
   * @return The orientation.
   */
  @java.lang.Override
  public double getOrientation() {
    return orientation_;
  }

  public static final int VX_FIELD_NUMBER = 5;
  private double vx_ = 0D;
  /**
   * <code>double vx = 5;</code>
   * @return The vx.
   */
  @java.lang.Override
  public double getVx() {
    return vx_;
  }

  public static final int VY_FIELD_NUMBER = 6;
  private double vy_ = 0D;
  /**
   * <code>double vy = 6;</code>
   * @return The vy.
   */
  @java.lang.Override
  public double getVy() {
    return vy_;
  }

  public static final int VORIENTATION_FIELD_NUMBER = 7;
  private double vorientation_ = 0D;
  /**
   * <code>double vorientation = 7;</code>
   * @return The vorientation.
   */
  @java.lang.Override
  public double getVorientation() {
    return vorientation_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (robotId_ != 0) {
      output.writeUInt32(1, robotId_);
    }
    if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
      output.writeDouble(2, x_);
    }
    if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
      output.writeDouble(3, y_);
    }
    if (java.lang.Double.doubleToRawLongBits(orientation_) != 0) {
      output.writeDouble(4, orientation_);
    }
    if (java.lang.Double.doubleToRawLongBits(vx_) != 0) {
      output.writeDouble(5, vx_);
    }
    if (java.lang.Double.doubleToRawLongBits(vy_) != 0) {
      output.writeDouble(6, vy_);
    }
    if (java.lang.Double.doubleToRawLongBits(vorientation_) != 0) {
      output.writeDouble(7, vorientation_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (robotId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, robotId_);
    }
    if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, x_);
    }
    if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, y_);
    }
    if (java.lang.Double.doubleToRawLongBits(orientation_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, orientation_);
    }
    if (java.lang.Double.doubleToRawLongBits(vx_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, vx_);
    }
    if (java.lang.Double.doubleToRawLongBits(vy_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, vy_);
    }
    if (java.lang.Double.doubleToRawLongBits(vorientation_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, vorientation_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Protobuf.Robot)) {
      return super.equals(obj);
    }
    Protobuf.Robot other = (Protobuf.Robot) obj;

    if (getRobotId()
        != other.getRobotId()) return false;
    if (java.lang.Double.doubleToLongBits(getX())
        != java.lang.Double.doubleToLongBits(
            other.getX())) return false;
    if (java.lang.Double.doubleToLongBits(getY())
        != java.lang.Double.doubleToLongBits(
            other.getY())) return false;
    if (java.lang.Double.doubleToLongBits(getOrientation())
        != java.lang.Double.doubleToLongBits(
            other.getOrientation())) return false;
    if (java.lang.Double.doubleToLongBits(getVx())
        != java.lang.Double.doubleToLongBits(
            other.getVx())) return false;
    if (java.lang.Double.doubleToLongBits(getVy())
        != java.lang.Double.doubleToLongBits(
            other.getVy())) return false;
    if (java.lang.Double.doubleToLongBits(getVorientation())
        != java.lang.Double.doubleToLongBits(
            other.getVorientation())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROBOT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getRobotId();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getX()));
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getY()));
    hash = (37 * hash) + ORIENTATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getOrientation()));
    hash = (37 * hash) + VX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVx()));
    hash = (37 * hash) + VY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVy()));
    hash = (37 * hash) + VORIENTATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getVorientation()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Protobuf.Robot parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Robot parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Robot parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Robot parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Robot parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Protobuf.Robot parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Protobuf.Robot parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Robot parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Protobuf.Robot parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Protobuf.Robot parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Protobuf.Robot parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Protobuf.Robot parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Protobuf.Robot prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Protobuf.Robot}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Protobuf.Robot)
      Protobuf.RobotOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Robot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Robot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Protobuf.Robot.class, Protobuf.Robot.Builder.class);
    }

    // Construct using Protobuf.Robot.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      robotId_ = 0;
      x_ = 0D;
      y_ = 0D;
      orientation_ = 0D;
      vx_ = 0D;
      vy_ = 0D;
      vorientation_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Protobuf.FIRASimVisionMessage.internal_static_Protobuf_Robot_descriptor;
    }

    @java.lang.Override
    public Protobuf.Robot getDefaultInstanceForType() {
      return Protobuf.Robot.getDefaultInstance();
    }

    @java.lang.Override
    public Protobuf.Robot build() {
      Protobuf.Robot result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Protobuf.Robot buildPartial() {
      Protobuf.Robot result = new Protobuf.Robot(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Protobuf.Robot result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.robotId_ = robotId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.orientation_ = orientation_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.vx_ = vx_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.vy_ = vy_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.vorientation_ = vorientation_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Protobuf.Robot) {
        return mergeFrom((Protobuf.Robot)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Protobuf.Robot other) {
      if (other == Protobuf.Robot.getDefaultInstance()) return this;
      if (other.getRobotId() != 0) {
        setRobotId(other.getRobotId());
      }
      if (other.getX() != 0D) {
        setX(other.getX());
      }
      if (other.getY() != 0D) {
        setY(other.getY());
      }
      if (other.getOrientation() != 0D) {
        setOrientation(other.getOrientation());
      }
      if (other.getVx() != 0D) {
        setVx(other.getVx());
      }
      if (other.getVy() != 0D) {
        setVy(other.getVy());
      }
      if (other.getVorientation() != 0D) {
        setVorientation(other.getVorientation());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              robotId_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 17: {
              x_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              y_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              orientation_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              vx_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              vy_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              vorientation_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int robotId_ ;
    /**
     * <code>uint32 robot_id = 1;</code>
     * @return The robotId.
     */
    @java.lang.Override
    public int getRobotId() {
      return robotId_;
    }
    /**
     * <code>uint32 robot_id = 1;</code>
     * @param value The robotId to set.
     * @return This builder for chaining.
     */
    public Builder setRobotId(int value) {

      robotId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 robot_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRobotId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      robotId_ = 0;
      onChanged();
      return this;
    }

    private double x_ ;
    /**
     * <code>double x = 2;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }
    /**
     * <code>double x = 2;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(double value) {

      x_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double x = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x_ = 0D;
      onChanged();
      return this;
    }

    private double y_ ;
    /**
     * <code>double y = 3;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }
    /**
     * <code>double y = 3;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(double value) {

      y_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double y = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000004);
      y_ = 0D;
      onChanged();
      return this;
    }

    private double orientation_ ;
    /**
     * <code>double orientation = 4;</code>
     * @return The orientation.
     */
    @java.lang.Override
    public double getOrientation() {
      return orientation_;
    }
    /**
     * <code>double orientation = 4;</code>
     * @param value The orientation to set.
     * @return This builder for chaining.
     */
    public Builder setOrientation(double value) {

      orientation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double orientation = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrientation() {
      bitField0_ = (bitField0_ & ~0x00000008);
      orientation_ = 0D;
      onChanged();
      return this;
    }

    private double vx_ ;
    /**
     * <code>double vx = 5;</code>
     * @return The vx.
     */
    @java.lang.Override
    public double getVx() {
      return vx_;
    }
    /**
     * <code>double vx = 5;</code>
     * @param value The vx to set.
     * @return This builder for chaining.
     */
    public Builder setVx(double value) {

      vx_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double vx = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVx() {
      bitField0_ = (bitField0_ & ~0x00000010);
      vx_ = 0D;
      onChanged();
      return this;
    }

    private double vy_ ;
    /**
     * <code>double vy = 6;</code>
     * @return The vy.
     */
    @java.lang.Override
    public double getVy() {
      return vy_;
    }
    /**
     * <code>double vy = 6;</code>
     * @param value The vy to set.
     * @return This builder for chaining.
     */
    public Builder setVy(double value) {

      vy_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double vy = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVy() {
      bitField0_ = (bitField0_ & ~0x00000020);
      vy_ = 0D;
      onChanged();
      return this;
    }

    private double vorientation_ ;
    /**
     * <code>double vorientation = 7;</code>
     * @return The vorientation.
     */
    @java.lang.Override
    public double getVorientation() {
      return vorientation_;
    }
    /**
     * <code>double vorientation = 7;</code>
     * @param value The vorientation to set.
     * @return This builder for chaining.
     */
    public Builder setVorientation(double value) {

      vorientation_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double vorientation = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearVorientation() {
      bitField0_ = (bitField0_ & ~0x00000040);
      vorientation_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Protobuf.Robot)
  }

  // @@protoc_insertion_point(class_scope:Protobuf.Robot)
  private static final Protobuf.Robot DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Protobuf.Robot();
  }

  public static Protobuf.Robot getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Robot>
      PARSER = new com.google.protobuf.AbstractParser<Robot>() {
    @java.lang.Override
    public Robot parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Robot> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Robot> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Protobuf.Robot getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

