// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FIRASimVisionMessage.proto

package Protobuf;

public interface RobotOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Protobuf.Robot)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 robot_id = 1;</code>
   * @return The robotId.
   */
  int getRobotId();

  /**
   * <code>double x = 2;</code>
   * @return The x.
   */
  double getX();

  /**
   * <code>double y = 3;</code>
   * @return The y.
   */
  double getY();

  /**
   * <code>double orientation = 4;</code>
   * @return The orientation.
   */
  double getOrientation();

  /**
   * <code>double vx = 5;</code>
   * @return The vx.
   */
  double getVx();

  /**
   * <code>double vy = 6;</code>
   * @return The vy.
   */
  double getVy();

  /**
   * <code>double vorientation = 7;</code>
   * @return The vorientation.
   */
  double getVorientation();
}
